### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [SSbug696/OpenGL-media-player.-Libvlc-and-qt#1]
Hi @SSbug696 .. I'm a graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo design for it if you allow me. I'll be doing it as a gift for free to your awesome project.
Best regard. Mirza zulfan.

**Comment by SSbug696** [comment]
Hi, Bro! =)  I am grateful to you for the response.
It's great that you're supporting open source. But that project was created
exclusively for educational purposes and I now just don't have time to
finished this product. =(



2018-07-30 13:45 GMT+03:00 Mirza Zulfan <notifications@github.com>:

**Comment by mirzazulfan** [comment]
Thanks for your response sir. I'll show it to you.

**Comment by mirzazulfan** [comment]
Hi @SSbug696 .. I've designed a logo for you project,, what do you think ? if you have an idea please share with me, it would be better for me. 
![open media player](https://user-images.githubusercontent.com/36124339/43439696-9198389c-94be-11e8-8485-22057f286f5c.png)

**Comment by SSbug696** [comment]
let's take the blue one!)

**Comment by mirzazulfan** [comment]
Hi @SSbug696, What do you think about this?
![open media player](https://user-images.githubusercontent.com/36124339/45997766-e99b5c80-c0ca-11e8-9e15-6ba995196aff.png)

**Comment by SSbug696** [comment]
2 number!) right

**Comment by mirzazulfan** [comment]
Hi, @SSbug696 I've created a pr. #2 
Thanks! If you need to change in the future, dont hesitate to cantact me, Email: mirzazulfan@gmail.com
